#!/usr/bin/env bash
set -euo pipefail

git clone git@github.com:Estatelab/elab-mgmt-projects.git
git clone git@github.com:Estatelab/elab-core-iac.git
git clone git@github.com:Estatelab/elab-story-debtor.git
git clone git@github.com:Estatelab/elab-tech-iac.git
git clone git@github.com:Estatelab/elab-tech-dal-counterparts.git
git clone git@github.com:Estatelab/elab-workflow-compose-acr-ci.git
git clone git@github.com:Estatelab/elab-tech-svc-iam.git
git clone git@github.com:Estatelab/elab-package-navigator.git
git clone git@github.com:Estatelab/elab-package-api-commons.git
git clone git@github.com:Estatelab/elab-tech-svc-signatories.git
git clone git@github.com:Estatelab/elab-package-counterparts.git
git clone git@github.com:Estatelab/elab-tech-dal-assets.git
git clone git@github.com:Estatelab/elab-package-assets.git
git clone git@github.com:Estatelab/elab-package-events.git
git clone git@github.com:Estatelab/elab-package-iam.git
git clone git@github.com:Estatelab/elab-tech-web.git
git clone git@github.com:Estatelab/elab-package-organization-hub.git
git clone git@github.com:Estatelab/elab-tech-svc-organization-hub.git
git clone git@github.com:Estatelab/elab-tech-dal-relationship.git
git clone git@github.com:Estatelab/elab-package-graph-relationship.git
git clone git@github.com:Estatelab/elab-package-identity.git
git clone git@github.com:Estatelab/elab-tech-persistence-graph.git
git clone git@github.com:Estatelab/elab-tech-epicenter.git
git clone git@github.com:Estatelab/elab-tech-persistence-postgres.git
git clone git@github.com:Estatelab/elab-tech-persistence-elab-stack.git
git clone git@github.com:Estatelab/elab-tech-svc-estates.git
git clone git@github.com:Estatelab/elab-tech-dal-assets-ledger.git
git clone git@github.com:Estatelab/elab-package-assets-ledger.git
git clone git@github.com:Estatelab/elab-package-leases.git
git clone git@github.com:Estatelab/elab-tech-dal-leases.git
git clone git@github.com:Estatelab/elab-package-cpi-adjustment.git
git clone git@github.com:Estatelab/elab-terraform-aws-s3-backend.git
git clone git@github.com:Estatelab/elab-package-testing-utilities.git
git clone git@github.com:Estatelab/elab-tech-svc-financials.git
git clone git@github.com:Estatelab/elab-tech-svc-letting.git
git clone git@github.com:Estatelab/elab-package-graph-mutator.git
git clone git@github.com:Estatelab/elab-tech-job-initialize-organization.git
git clone git@github.com:Estatelab/elab-package-common.git
git clone git@github.com:Estatelab/elab-tech-job-asset-constructor.git
git clone git@github.com:Estatelab/elab-tech-job-verify-email.git
git clone git@github.com:Estatelab/elab-tech-svc-events.git
git clone git@github.com:Estatelab/elab-terraform-aws-datadog-integration.git
git clone git@github.com:Estatelab/elab-tech-job-event-archiver.git
git clone git@github.com:Estatelab/elab-terraform-aws-ecr.git
git clone git@github.com:Estatelab/elab-terraform-aws-ecs-environment.git
git clone git@github.com:Estatelab/elab-terraform-aws-ecs-container-definition.git
git clone git@github.com:Estatelab/elab-terraform-aws-ecs-service.git
git clone git@github.com:Estatelab/elab-terraform-aws-neptune.git
git clone git@github.com:Estatelab/elab-terraform-datadog-monitors.git
git clone git@github.com:Estatelab/elab-package-lambda-common.git
git clone git@github.com:Estatelab/elab-tech-job-reset-password.git
git clone git@github.com:Estatelab/elab-tech-job-add-organization-member.git
git clone git@github.com:Estatelab/elab-tech-svc-reporting.git
git clone git@github.com:Estatelab/elab-tech-job-event-historizer.git
git clone git@github.com:Estatelab/elab-terraform-datadog-synthetics.git
git clone git@github.com:Estatelab/elab-tech-job-update-lease.git
git clone git@github.com:Estatelab/elab-tech-job-asset-destructor.git
git clone git@github.com:Estatelab/elab-tech-job-asset-reconstructor.git
git clone git@github.com:Estatelab/elab-tech-job-cpi-adjustor.git
git clone git@github.com:Estatelab/elab-tech-job-billing-generator.git
git clone git@github.com:Estatelab/elab-package-document-hub.git
git clone git@github.com:Estatelab/elab-tech-svc-document-hub.git
git clone git@github.com:Estatelab/elab-package-billing-generator.git
git clone git@github.com:Estatelab/elab-tech-job-lease-generator.git
git clone git@github.com:Estatelab/elab-tech-job-lease-destructor.git
git clone git@github.com:Estatelab/elab-tech-integration-power-office.git
git clone git@github.com:Estatelab/elab-package-integrations.git
git clone git@github.com:Estatelab/elab-tech-integration-finago.git
git clone git@github.com:Estatelab/elab-tech-integration-tripletex.git
git clone git@github.com:Estatelab/elab-tech-job-agent-generator.git
git clone git@github.com:Estatelab/elab-poc-integrations.git
